// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmpXpOr9Fm_uv0u5E8oJO3YT1ekrTACg',
    appId: '1:335081283783:web:ce52e2a93a78d01bdc1ee2',
    messagingSenderId: '335081283783',
    projectId: 'sportspace-uni',
    authDomain: 'sportspace-uni.firebaseapp.com',
    storageBucket: 'sportspace-uni.firebasestorage.app',
    measurementId: 'G-SGTSPPHJFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0c8k83L6TsZEkXdKnUcui7TnuzojlWcI',
    appId: '1:335081283783:android:0286e121e4dc5421dc1ee2',
    messagingSenderId: '335081283783',
    projectId: 'sportspace-uni',
    storageBucket: 'sportspace-uni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrf6dfzzGx9R2YTMnUbFgldb237CL0ecU',
    appId: '1:335081283783:ios:10c899576b92aea6dc1ee2',
    messagingSenderId: '335081283783',
    projectId: 'sportspace-uni',
    storageBucket: 'sportspace-uni.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrf6dfzzGx9R2YTMnUbFgldb237CL0ecU',
    appId: '1:335081283783:ios:10c899576b92aea6dc1ee2',
    messagingSenderId: '335081283783',
    projectId: 'sportspace-uni',
    storageBucket: 'sportspace-uni.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhmpXpOr9Fm_uv0u5E8oJO3YT1ekrTACg',
    appId: '1:335081283783:web:410dd9828a5b94a0dc1ee2',
    messagingSenderId: '335081283783',
    projectId: 'sportspace-uni',
    authDomain: 'sportspace-uni.firebaseapp.com',
    storageBucket: 'sportspace-uni.firebasestorage.app',
    measurementId: 'G-BQS6XH8VEM',
  );
}
